# Generated by Django 5.2.12 on 2026-05-08 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athens_tenant_id', models.IntegerField(db_index=True)),
                ('admin_role', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('attendance_date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('working', 'Working'), ('checked_out', 'Checked Out')], default='absent', max_length=20)),
                ('check_in_lat', models.FloatField(blank=True, null=True)),
                ('check_in_lng', models.FloatField(blank=True, null=True)),
                ('check_out_lat', models.FloatField(blank=True, null=True)),
                ('check_out_lng', models.FloatField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('correction_note', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_attendances', to=settings.AUTH_USER_MODEL)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_attendance',
                'ordering': ['-attendance_date', 'admin__email'],
                'indexes': [models.Index(fields=['athens_tenant_id', 'attendance_date'], name='admin_atten_athens__e8ef4b_idx'), models.Index(fields=['admin', 'attendance_date'], name='admin_atten_admin_i_4a1697_idx'), models.Index(fields=['status'], name='admin_atten_status_138d95_idx')],
                'unique_together': {('admin', 'attendance_date')},
            },
        ),
    ]
