# Generated by Django 5.2.12 on 2026-05-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbt', '0004_add_training_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolboxtalk',
            name='training_type',
            field=models.CharField(choices=[('inspection_training', 'Inspection Training'), ('job_training', 'Job Training'), ('induction_training', 'Induction Training'), ('safety_training', 'Safety Training'), ('toolbox_training', 'Toolbox Training')], db_index=True, default='toolbox_training', max_length=50, verbose_name='Training Type'),
        ),
    ]
