# Generated by Django 5.2.12 on 2026-05-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyobservation', '0006_safetyobservationaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyobservation',
            name='observationStatus',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('pending_verification', 'Pending Verification'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=50),
        ),
    ]
